---
  - name: Configure and deploy application
    hosts: webservers
    become: true
  
    tasks:
      - name: Install Docker
        apt:
          name: docker.io
          state: present
  
      - name: Deploy application
        copy:
          src: ../../src
          dest: /var/www/myapp
  