name: "Docker Build and Publish"

on:
  push:
    branches:
      - main #pull request to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: |
          docker build -t yelghom/webgoat:latest .

      - name: Push the Docker image
        run: |
          docker push yelghom/webgoat:latest
